/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { ArrowRight, MessageCircle } from "lucide-react";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { FibrePlanCard, FiveGPlanCard } from "@/components/pages/PlanCards";
import { fibrePackages, fiveGPackages } from "@/lib/packages";
import { defaultWhatsAppLink } from "@/lib/whatsapp";

export const metadata: Metadata = { title: "Home Internet Packages | ConnectKenya", description: "Compare Home Fibre and 5G internet plans, speeds and prices, then contact Jackie to check availability." };

export default function PackagesPage() {
  return <><Header /><main className="packages-page"><section className="packages-page-hero"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><p className="mb-4 text-xs font-extrabold uppercase tracking-[0.18em] text-[#00a651]">Home Internet Packages</p><h1 className="max-w-3xl text-4xl font-black tracking-[-0.055em] text-[#111827] sm:text-6xl">Choose the Internet Package That Fits Your Home</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5f6b65]">Compare available Home Fibre and 5G internet plans and contact Jackie to check availability in your area.</p></div></section><section className="packages-page-section"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="mb-10"><p className="mb-3 text-xs font-extrabold uppercase tracking-[0.18em] text-[#00a651]">Fixed home internet</p><h2 className="text-3xl font-extrabold text-[#111827] sm:text-4xl">Home Fibre packages</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{fibrePackages.map((fibrePackage) => <FibrePlanCard key={fibrePackage.name} fibrePackage={fibrePackage} />)}</div></div></section><section className="packages-page-5g"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="mb-10"><p className="mb-3 text-xs font-extrabold uppercase tracking-[0.18em] text-[#8ce0af]">Wireless home internet</p><h2 className="text-3xl font-extrabold text-white sm:text-4xl">5G Home Internet packages</h2><p className="mt-4 max-w-2xl leading-7 text-white/70">Choose a speed that suits your connected home. Availability depends on 5G coverage in your area.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{fiveGPackages.map((plan) => <FiveGPlanCard key={plan.speed} plan={plan} />)}</div></div></section><section className="packages-page-cta"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 lg:flex-row lg:items-center lg:justify-between lg:px-8 lg:py-20"><div><h2 className="text-3xl font-extrabold text-white">Not Sure Which Package to Choose?</h2><p className="mt-4 max-w-2xl leading-7 text-white/75">Tell Jackie where you live and how you use the internet, and she can help you identify suitable available options.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="/#coverage" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#111827] px-5 text-sm font-extrabold text-white hover:bg-[#075b35]">Check Coverage <ArrowRight size={17} /></a><a href={defaultWhatsAppLink} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-extrabold text-[#075b35] hover:bg-[#e8f7ee]"><MessageCircle size={17} />WhatsApp Jackie</a></div></div></section></main><Footer /></>;
}
